# Generated by Django 4.1 on 2022-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('first_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_name', models.CharField(default=True, max_length=200)),
            ],
        ),
    ]
