# Generated by Django 4.1 on 2022-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_musician_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
